Crawl-3492: Port freshdesk perl script to Go
Siteimprove/freshdesk-poster pull request #3
Opened 2022-04-19 12:31 UTC by msk-siteimprove

Ports the Perl Freshdesk script behaviour to Go code and makes it possible to deploy it as a cronjob in Kubernetes using the Makefile.

**Notes**:
- See [readme.md](../blob/crawl-3492-port-freshdesk-perl-script/README.md) for details about the implementation.

- See Perl script: http://intgit.siteimprove.systems/Siteimprove/siteimprove/blob/master/script/freshdesk/post_freshdesk_ticket.pl

- See data: In the `si` db you can see the data by doing: `select * from CRAWL_PROBLEM_FRESHDESK_EMAIL order by id asc;`

**Missing**:
- In case 5 attempts have been made to send a row to the Freshdesk API, the row will be in a state with `status=W` and `try_cnt=4` which  means it will not be touched by the program again -- what do we want to do with these rows? Currently the max `try_cnt` observed in the database is 4.
- Run interval should be tuned in `deploy.yaml.template`.
- Cleanup age-threshold should be tuned in `main.go`.

2022-04-19 13:28 UTC, TueHaulund requested changes
Looks real good so far - added some general comments about the code.

2022-04-19 13:28 UTC, TueHaulund commented on README.md
> +so primarliy due to legacy reasons but it also works as a way to make operations idempotent on the
Typo

2022-04-19 13:28 UTC, TueHaulund commented on cmd/cli/main.go
> +	ctx, cancel := context.WithTimeout(context.TODO(), sqlgwTimeout)
Functionally the same but semantically this should probably just be `context.Background()`

2022-04-19 13:28 UTC, TueHaulund commented on cmd/cli/main.go
> +func createFreshdeskAuthToken(apikey string) string {
Maybe this should be a private method on the Freshdesk client object - then you can just pass in the API key and nobody other than the Freshdesk client needs to know the specifics about how this key should be encoded.

2022-04-19 13:28 UTC, TueHaulund commented on cmd/cli/main.go
> +func postToFreshdesk(ctx context.Context, rows []sqlgateway.CrawlProblem, dbclient *sqlgateway.SqlClient, fdclient *freshdesk.HttpClient) {
This could be a method on the Freshdesk client object rather than a freestanding function here in main.go

2022-04-19 13:28 UTC, TueHaulund commented on cmd/cli/main.go
> +func setRowStatusError(ctx context.Context, rowId int64, dbclient *sqlgateway.SqlClient) {
Are these functions necessary? Seems they just wrap the functions already present on the dbclient object? Why not call those directly from `postToFreshdesk`?

2022-04-19 13:28 UTC, TueHaulund commented on cmd/cli/main.go
> +	deleteRowsOlderThan(ctx, 2000, dbclient)
Threshold should either be a const variable (so you can give it a name that also specifies the units, right now it is not possible to know that the number here refers to days)

Or it should be a program parameter

2022-04-19 13:28 UTC, TueHaulund commented on deploy.yaml.template
> +apiVersion: v1
This single YAML file works when you're only deploying to ix-cph/prod.

But this probably will not scale nicely into 2-3 environments across 4 datacenters.

It might be necessary to create a setup like we have in crawler-robin and the other repos, although I know Harald is also planning a brand new "deployment" repo so maybe coordinate wiht him to avoid wasting effort.

2022-04-19 13:28 UTC, TueHaulund commented on cmd/cli/main.go
> +	apiKey, err := dbclient.GetFreshdeskApiKey(ctx)
Maybe its time we move the Freshdesk API key into a k8s secret instead of loading it from the database.

(Don't delete the API key from the DB until the old Freshdesk setup is decommissioned)

2022-04-20 07:32 UTC, msk-siteimprove commented on deploy.yaml.template
> +apiVersion: v1
I initially went down that road, but after realizing/talking to the guys about having a more centralized way of deploying, I decided to do a minimal setup, but might not be the best approach still.

I believe there is already a ticket to setup this centralized kind of deployment so it's coming.

2022-04-20 07:33 UTC, msk-siteimprove commented on cmd/cli/main.go
> +	deleteRowsOlderThan(ctx, 2000, dbclient)
Yeah probably parameter is the cleanest way. Question is how many days back in time we want to preserve.

2022-04-20 07:34 UTC, msk-siteimprove commented on cmd/cli/main.go
> +func setRowStatusError(ctx context.Context, rowId int64, dbclient *sqlgateway.SqlClient) {
Yeah I tried to strreamline some error handling given that most of these calls are made multiple times which translates to a lot of error handling/logging in the `postToFreshdesk` function.

2022-04-20 07:39 UTC, msk-siteimprove commented on cmd/cli/main.go
> +	apiKey, err := dbclient.GetFreshdeskApiKey(ctx)
Excellent excellent.

2022-04-20 11:50 UTC, msk-siteimprove commented on README.md
> +so primarliy due to legacy reasons but it also works as a way to make operations idempotent on the
See bf8bbc54624182fa3620f4f193e454cb87e38d3f.

2022-04-20 11:51 UTC, msk-siteimprove commented on cmd/cli/main.go
> +	ctx, cancel := context.WithTimeout(context.TODO(), sqlgwTimeout)
See 4da1d2fb1d3e57f3aa338c5d826cf10bf901fc47.

2022-04-20 11:52 UTC, msk-siteimprove commented on cmd/cli/main.go
> +func createFreshdeskAuthToken(apikey string) string {
I moved it there as a public function in the package. See 4da1d2fb1d3e57f3aa338c5d826cf10bf901fc47.

2022-04-20 11:52 UTC, msk-siteimprove commented on cmd/cli/main.go
> +func postToFreshdesk(ctx context.Context, rows []sqlgateway.CrawlProblem, dbclient *sqlgateway.SqlClient, fdclient *freshdesk.HttpClient) {
I moved it there as a public function in the package. See 4da1d2fb1d3e57f3aa338c5d826cf10bf901fc47.

2022-04-20 11:53 UTC, msk-siteimprove commented on cmd/cli/main.go
> +func setRowStatusError(ctx context.Context, rowId int64, dbclient *sqlgateway.SqlClient) {
I made the error handling more explicit in `postToFreshdesk` now. See 4da1d2fb1d3e57f3aa338c5d826cf10bf901fc47 in `freshdesk` package.

2022-04-20 11:54 UTC, msk-siteimprove commented on cmd/cli/main.go
> +	deleteRowsOlderThan(ctx, 2000, dbclient)
Changed it to be a CLI param. See 4da1d2fb1d3e57f3aa338c5d826cf10bf901fc47.

2022-04-20 11:55 UTC, msk-siteimprove commented on cmd/cli/main.go
> +	apiKey, err := dbclient.GetFreshdeskApiKey(ctx)
I added the api key to LastPass and as a K8s secret and this Go program now takes it as a CLI param. See 4da1d2fb1d3e57f3aa338c5d826cf10bf901fc47.

2022-04-22 11:11 UTC, msk-siteimprove commented
Tests successfully conducted so far: 
```
**OK** 1. a) happy path               (post successfully to fd , fd result looks good, and status=d, sent_ts=now())
**OK** 3. invalid json path local     (invalid json status=error)
**OK** 5. a) http 403 request error   (status=E)
**OK** 5. b) request http             (status=N)
**OK** 6. clean up path               (a row is older than n days and is removed)
**OK** 7. case crash/expired row      (expired row is updated to status=N and picked up immediately)
**OK** 8. case status=N, try_cnt=5    (transitioning from try_cnt=4 to 5, not picked up again)
```

2022-05-10 07:45 UTC, TueHaulund approved these changes

2022-05-10 07:59 UTC, merged